name: Assign IP to Current Instance

on:
  workflow_dispatch:
    inputs:
      service_id:
        description: Service for which to create an instance
        required: true

jobs:
  assign:
    name: Assign IP
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify service id is valid
        env:
          CONFIGURATION_PATH: ./services/${{ github.event.inputs.service_id }}/configuration.json
        run: |
          if [ ! -f "$CONFIGURATION_PATH" ]; then
            echo "Configuration for service ${{ github.event.inputs.service_id }} not found: $CONFIGURATION_PATH"
            exit 1
          fi

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs --quiet
      - name: Get floating IP
        id: ip
        env:
          INSTANCE_COLLECTION_TAG: ${{ github.event.inputs.service_id }}
        run: |
          echo "::set-output name=value::$(php bin/console app:ip:get)"

      - name: Re-assign IP if found
        if: ${{ steps.ip.outputs.value != '' }}
        env:
          INSTANCE_COLLECTION_TAG: ${{ github.event.inputs.service_id }}
          COMMAND: "php bin/console app:ip:assign"
        run: ./ci/scripts/execute-command-output-json.sh

      - name: Create IP if none found
        if: ${{ steps.ip.outputs.value == '' }}
        env:
          INSTANCE_COLLECTION_TAG: ${{ github.event.inputs.service_id }}
          COMMAND: "php bin/console app:ip:create"
        run: ./ci/scripts/execute-command-output-json.sh
