name: Assign IP to Current Instance

on:
  workflow_dispatch:
    inputs:
      service_id:
        description: Service for which to create an instance
        required: true

jobs:
  assign:
    name: Assign IP
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Verify service id is valid
        run: |
          php bin/console app:service-configuration:exists \
          --service-id="${{ github.event.inputs.service_id }}"

      - name: Get floating IP
        id: ip
        run: |
          echo "::set-output name=value::$(
            php bin/console app:ip:get \
            --service-id="${{ github.event.inputs.service_id }}"
          )"

      - name: Re-assign IP if found
        if: ${{ steps.ip.outputs.value != '' }}
        run: |
          php bin/console app:ip:assign \
          --service-id="${{ github.event.inputs.service_id }}"

      - name: Create IP if none found
        if: ${{ steps.ip.outputs.value == '' }}
        run: |
          php bin/console app:ip:create \
          --service-id="${{ github.event.inputs.service_id }}"
