name: service.configure

on:
  repository_dispatch:
    types: [service-configure]
  workflow_dispatch:
    inputs:
      service_id:
        description: The service for which the configuration is being stored
        required: true
      state_url:
        description: URL from which to get instance state
        required: false
      health_check_url:
        description: URL from which to check that an instance is healthy
        required: false

jobs:
  store-service-configuration:
    name: Store ${{ github.event.inputs.service_id }}
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        id: setup
        env:
          IS_WORKFLOW_DISPATCH_EVENT: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if [ "true" = "$IS_WORKFLOW_DISPATCH_EVENT" ]; then
            echo "::set-output name=service_id::${{ github.event.inputs.service_id }}"
            echo "::set-output name=health_check_url::${{ github.event.inputs.health_check_url }}"
            echo "::set-output name=state_url::${{ github.event.inputs.state_url }}"
          else
            echo "::set-output name=service_id::${{ github.event.client_payload.service_id }}"
            echo "::set-output name=health_check_url::${{ github.event.client_payload.health_check_url }}"
            echo "::set-output name=state_url::${{ github.event.client_payload.state_url }}"
          fi

      - name: Output setup
        env:
          VALUES: ${{ toJson(steps.setup.outputs) }}
        run: echo "$VALUES"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs --quiet

      - name: Store
        run: |
          php bin/console app:service-configuration:set \
          --service-id='${{ steps.setup.outputs.service_id }}' \
          --health-check-url='${{ steps.setup.outputs.health_check_url }}' \
          --state-url='${{ steps.setup.outputs.state_url }}'

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: services/${{ steps.setup.outputs.service_id }}/*
          commit_message: "Automatic configuration update for ${{ steps.setup.outputs.service_id }}"
