name: service.configure

on:
  repository_dispatch:
    types: [service-configure]
  workflow_dispatch:
    inputs:
      service_id:
        description: The service for which the configuration is being stored
        required: true
      state_url:
        description: URL from which to get instance state
        required: false
      health_check_url:
        description: URL from which to check that an instance is healthy
        required: false

jobs:
  store-service-configuration:
    name: Store ${{ github.event.inputs.service_id }} ${{ github.event.client_payload.service_id }}
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        env:
          IS_WORKFLOW_DISPATCH_EVENT: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if [ "true" = "$IS_WORKFLOW_DISPATCH_EVENT" ]; then
            {
              echo "service_id=${{ github.event.inputs.service_id }}"
              echo "health_check_url=${{ github.event.inputs.health_check_url }}"
              echo "state_url=${{ github.event.inputs.state_url }}"          
            } >> "$GITHUB_ENV"
          else
            {
              echo "service_id=${{ github.event.client_payload.service_id }}"
              echo "health_check_url=${{ github.event.client_payload.health_check_url }}"
              echo "state_url=${{ github.event.client_payload.state_url }}"          
            } >> "$GITHUB_ENV"          
          fi

      - name: Output setup
        run: |
          echo "service_id=${{ env.service_id }}"
          echo "health_check_url=${{ env.health_check_url }}"
          echo "state_url=${{ env.state_url }}"            

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Store
        run: |
          php bin/console app:service-configuration:set \
          --service-id='${{ env.service_id }}' \
          --health-check-url='${{ env.health_check_url }}' \
          --state-url='${{ env.state_url }}'

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: services/${{ env.service_id }}/*
          commit_message: "Automatic configuration update for ${{ env.service_id }}"
