name: test.service.configure

on:
  workflow_dispatch:

jobs:
  test-store-service-configuration:
    name: Test Store Service Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Create service id
        run: |
          SERVICE_ID=$(md5sum <<< "$RANDOM" | cut -d ' ' -f 1)
          
          echo "service_id=$SERVICE_ID" >> "$GITHUB_ENV"  

      - name: Output service id
        run: |
          echo "service_id=${{ env.service_id }}"         

      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify service does not have a configuration directory
        run: |     
          SERVICE_DIRECTORY="services/${{ env.service_id }}"
          
          if [ -d "$SERVICE_DIRECTORY" ] ; then
            echo "$SERVICE_DIRECTORY already exists."
            exit 1
          fi
          
          echo "$SERVICE_DIRECTORY does not exist."

      - name: Call service.configure
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run service.configure.yml \
          -r "$GITHUB_REF" \
          -f service_id="${{ env.service_id }}" \
          -f state_url="/state" \
          -f health_check_url="/health"

      - name: Wait for service.configure to finish
        run: |
          LIMIT=100
          TIMEOUT=$LIMIT          
          DELAY=10
          SERVICE_DIRECTORY="services/${{ env.service_id }}"
          
          until [ $TIMEOUT -le 0 ] || [ -d "$SERVICE_DIRECTORY" ] ; do
            # git pull --quiet
            echo "$SERVICE_DIRECTORY does not exist. Waiting $TIMEOUT seconds of $LIMIT ..."
            sleep $DELAY
            TIMEOUT=$(( TIMEOUT - DELAY ))
          done
          
          if [ $TIMEOUT -le 0 ] ; then
            echo "Timed out after $LIMIT seconds waiting for $SERVICE_DIRECTORY to exist."
            exit 1
          fi
